language: python

python:
  - "2.7"

services:
  - postgresql

env:
  - POSTGIS_VERSION=2

install:
  - sudo apt-get install postgresql-9.1-postgis -q

before_script:
  - psql -c 'create database teste;' -U postgres
  - psql -d teste -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql
  - psql -d teste -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql 
  - psql -d teste -f /usr/share/postgresql/9.1/contrib/postgis_comments.sql
  - pip install psycopg2 --use-mirrors

script:
  - cd src/tests
  - python runTests.py

notifications:
  email:
    recipients:
      - matheus1401@gmail.com
    on_success: always
    on_failure: always
