INSERT INTO FugaRota VALUES (1, 11, false, DEFAULT, NULL);
INSERT INTO FugaRota VALUES ("1", 10, false, DEFAULT, NULL);
INSERT INTO FugaRota VALUES (1, "10", false, DEFAULT, NULL);
INSERT INTO FugaRota VALUES (1, 10, 1, DEFAULT, NULL);
INSERT INTO FugaRota VALUES (1, 10, false, 2, NULL);
INSERT INTO FugaRota VALUES ("1", 10, false, DEFAULT, "2");
INSERT INTO FugaRota VALUES (NULL, 10, false, DEFAULT, NULL);
INSERT INTO FugaRota VALUES (1, NULL, false, DEFAULT, NULL);
INSERT INTO FugaRota VALUES (1, 10, NULL, DEFAULT, NULL);
INSERT INTO FugaRota VALUES (1, 10, false, NULL, NULL);
INSERT INTO FugaRota VALUES (10, false, DEFAULT, NULL);
INSERT INTO FugaRota VALUES (1, false, DEFAULT, NULL);
INSERT INTO FugaRota VALUES (1, 10, DEFAULT, NULL);
INSERT INTO FugaRota VALUES (1, 10, false, NULL);


